function applyNumberMask(input) { let value = input.value.replace(/\D/g, ''); if (value !== '') value = Number(value).toLocaleString('pt-BR'); input.value = value; }
function parseCleanNumber(elementId) { const val = document.getElementById(elementId).value; return val ? parseFloat(val.replace(/\./g, '').replace(',', '.')) || 0 : 0; }
function formatNumber(num) { return Math.round(num).toLocaleString('pt-BR'); }
function formatTime(totalSeconds) { const days=Math.floor(totalSeconds/86400), hours=Math.floor((totalSeconds%86400)/3600), minutes=Math.floor((totalSeconds%3600)/60), seconds=Math.round(totalSeconds%60); let s=''; if(days>0)s+=`${days}d `; if(hours>0||days>0)s+=`${hours}h `; if(minutes>0||hours>0||days>0)s+=`${minutes}m `; s+=`${seconds}s`; return s.trim(); }
function toggleSubmenu(event){ event.preventDefault(); const menuLink=event.currentTarget, submenu=menuLink.nextElementSibling, indicator=menuLink.querySelector('.submenu-indicator'); submenu.classList.toggle('open'); indicator.textContent=submenu.classList.contains('open')?'-':'+'; }
function changeLanguageSafe(lang){ localStorage.setItem('cod_lang',lang); const botSel=document.getElementById('settings-lang-dropdown'); if(botSel)botSel.value=lang; const t=(typeof translations!=='undefined'&&translations[lang])?translations[lang]:((typeof translations!=='undefined')?translations['en']:{}); document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.getAttribute('data-i18n'); if(t&&t[key])el.textContent=t[key];}); }
function setTheme(themeClass){ document.body.className=`app-layout ${themeClass}`; localStorage.setItem('cod_theme',themeClass); }
function renewSubscription(){ alert('Redirecting to secure subscription renewal gateway...'); }
window.addEventListener('DOMContentLoaded',()=>{ const lang=localStorage.getItem('cod_lang'); if(lang&&typeof changeLanguageSafe==='function')changeLanguageSafe(lang); const theme=localStorage.getItem('cod_theme'); if(theme)document.body.className=`app-layout ${theme}`; });
